config/routes.rb
Server::Application.routes.draw do

  resources :games do
    resources :points
    member do
      get :list_points
      get :found_points
      get :start # should be same as POST collection[param{:id => 'id'}
      get :end # should be same as POST collection[param{:id => 'id'}
    end
    collection do
      get :list_active
      post :add_point
      post :add_user
      post :start, :action => "start"
      post :end
    end
  end

  resources :users do
    member do
      post :check_location
      post :found_point
    end
    collection do
      post :check_location
      post :found_point
    end
  end

  resources :points
  

  root :to => "games#index"

end

app/models/point.rb
class Point
  include MongoMapper::Document

# {
#     'loc' : {
#         latitude: 34.2232,
#         longitude: -123.22
#     },
#     'user-action' 'Some text that describes what happens at this point',
#     'found-by' : [12, 122123, 12322]
#     'type' : 'checkpoint', 
#     'created' : date(),
#     'game-id' 1231234434
# }
  ensure_index [[:loc, '2d']]

  key :user_action, String
  key :found_by, Array
  key :type, String
  key :created_at, Date
  key :game_id, String
#  key :location, Location
  
  belongs_to :games

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  # GET /points
  # GET /points.xml
  def index
    @points = Point.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @points }
      format.json  { render :json => @points }
    end
  end

  # GET /points/1
  # GET /points/1.xml
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @point }
      format.json  { render :json => @point }
    end
  end

  # GET /points/new
  # GET /points/new.xml
  def new
    @point = Point.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @point }
      format.json  { render :json => @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.xml
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to(@point, :notice => 'Point was successfully created.') }
        format.xml  { render :xml => @point, :status => :created, :location => @point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
        format.json  { render :json => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.xml
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to(@point, :notice => 'Point was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
        format.json  { render :json => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.xml
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to(points_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end

###
## Starting non-standard functions
#

end

app/helpers/points_helper.rb
module PointsHelper
end

app/views/points/_form.html.erb
<%= form_for(@point) do |f| %>
  <% if @point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>

      <ul>
      <% @point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  User Action: <%=f.text_field :user_action %><br />
  Found By: <%= f.text_field :found_by.to_s %><br />
  Type: <%= f.text_field :type %><br />
  Created: <%= f.text_field :created_at %><br />
  Game Id: <%= f.text_field :game_id %><br />
  Location: <%#= f.text_field :location %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/edit.html.erb
<h1>Editing point</h1>

<%= render 'form' %>

<%= link_to 'Show', @point %> |
<%= link_to 'Back', points_path %>

app/views/points/index.html.erb
<h1>Listing points</h1>

<table>
  <tr>
    <th>User Action</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @points.each do |point| %>
  <tr>
    <td><%= point.user_action%>:</td>
    <td><%= link_to 'Show', point %></td>
    <td><%= link_to 'Edit', edit_point_path(point) %></td>
    <td><%= link_to 'Destroy', point, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Point', new_point_path %>

app/views/points/new.html.erb
<h1>New point</h1>

<%= render 'form' %>

<%= link_to 'Back', points_path %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

  User Action: <%=@point.user_action %><br />
  Found By: <%= @point.found_by.to_s %><br />
  Type: <%= @point.type %><br />
  Created: <%= @point.created_at %><br />
  Game Id: <%= @point.game_id %><br />
  Location: <%#= @point.location.to_s %><br />


<%= link_to 'Edit', edit_point_path(@point) %> |
<%= link_to 'Back', points_path %> |
<%= link_to 'Show JSON', point_path(@point, :format => "json") %>