config/routes.rb
Server::Application.routes.draw do

  resources :games do
    resources :points
    member do
      get :list_points
      get :found_points
      get :start # should be same as POST collection[param{:id => 'id'}
      get :end # should be same as POST collection[param{:id => 'id'}
    end
    collection do
      get :list_active
      post :add_point
      post :add_user
      post :start, :action => "start"
      post :end
    end
  end

  resources :users do
    member do
      post :check_location
      post :found_point
    end
    collection do
      post :check_location
      post :found_point
    end
  end

  resources :points
  

  root :to => "games#index"

end

app/models/game.rb
class Game
  include MongoMapper::Document

# {
# 	'_id': ObjectId('asdfafadsfas'),
# 	'name': 'Downtown Durham Track',
# 	'hare': '1233',
#         'co-hares' : [122, 222]
# 	'created' : date(),
# 	'started' : date()
#         'hounds' : [
# 		223, 2233, 445, 4556, 4456
#          ]
# 	'loc' : {
# 		latitude: 34.2232,
# 		longitude: -123.22
# 	},
# }

  key :name, String, :required => true
	key :hare, String, :required => true
  key :co_hares, Array
	key :created_at, Date
	key :started_at, Date
  key :hounds, Array
#  key :location, Location

  has_many :points
  
  # Use created_at and updated_at timestamps
  timestamps!

  # Define the Named Scopes
  #named_scope :active, lambda {|time| {:conditions => ["started_at != ?", nil] }}


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.xml
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @games }
      format.json  { render :json => @games }
    end
  end

    # GET /games/1
    # GET /games/1.xml
    # GET /games/1.json
    # output: HTTP OK + game (if successful)
    #  HTTP NOT_FOUND (if incorrect params),
    #  HTTP INTERNALSERVERERROR (if unforeseen error)
  def show
    @game = Game.find(params[:id])

    if @game.nil? 
      respond_to do |format|
        format.all { render :status => :not_found, :text => "Game not found." }
      end
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @game }
        format.json  { render :json => @game }
      end
    end
  end

  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
      format.json  { render :json => @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

    # POST /games
    # POST /games.xml
    # POST /games.json
    # input: game:{name:'game_name', hare:'hare-id'}
    # output: HTTP OK + game (if successful)
    #  HTTP BADREQUEST (if incorrect params),
    #  HTTP INTERNALSERVERERROR (if unforeseen error)
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to(@game, :notice => 'Game was successfully created.') }
        format.xml  { render :xml => @game, :status => :created_at, :location => @game }
        format.json  { render :json => @game, :status => :created_at, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
        format.json  { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(@game, :notice => 'Game was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
        format.json  { render :json => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end

###
## Starting non-standard functions
#
  
    # GET /games/list_active
    # GET /games/list_active.xml
    # GET /games/list_active.json
    # output: HTTP OK + array of active games (if successful)
    #  HTTP BADREQUEST (if incorrect params),
    #  HTTP INTERNALSERVERERROR (if unforeseen error)
  def list_active
    @games = Game.all.reject{|g| g.started_at.nil?}
    
    if @games.nil? 
      respond_to do |format|
        format.all { render :status => :not_found, :text => "No active games found." }
      end
    else
      respond_to do |format|
        format.html { render :action => "index", :html => @games }
        format.xml  { render :action => "index", :xml => @games }
        format.json  { render :index, :json => @games }
      end
    end
  end


    # POST /games/start
    # POST /games/start.xml
    # POST /games/start.json
    # input: game:{id:'game_id'}
    # 
    # GET /games/1/start
    # GET /games/1/start.xml
    # GET /games/1/start.json
    # output: HTTP OK (if successful)
    #  HTTP BADREQUEST (if incorrect params),
    #  HTTP INTERNALSERVERERROR (if unforeseen error)
  def start
    @game = Game.find(params[:id])
    
    respond_to do |format|
      if @game.nil? 
        format.all { render :status => :not_found, :text => "No game found of id #{params[:id]}" }
      else
        @game.started_at = DateTime.now()
        if @game.save
          format.html { render :action => "show", :html => @game, :notice => 'Game was successfully started.' }
          format.xml  { render :action => "show", :xml => @game }
          format.json  { render :action => "show", :json => @game }
        else
          format { render :action => "show" }
          format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
          format.json  { render :json => @game.errors, :status => :unprocessable_entity }
        end
      end
    end
  end


    # POST /games/end
    # POST /games/end.xml
    # POST /games/end.json
    # input: game:{id:'game_id'}
    # 
    # GET /games/1/end
    # GET /games/1/end.xml
    # GET /games/1/end.json
    # output: HTTP OK (if successful)
    #  HTTP BADREQUEST (if incorrect params),
    #  HTTP INTERNALSERVERERROR (if unforeseen error)
  def end
    @game = Game.find(params[:id])
    
    respond_to do |format|
      if @game.nil? 
        format.all { render :status => :not_found, :text => "No game found of id #{params[:id]}" }
      else
        @game.started_at = nil
        if @game.save
          format.html { render :action => "show", :html => @game, :notice => 'Game was successfully ended.' }
          format.xml  { render :action => "show", :xml => @game }
          format.json  { render :action => "show", :json => @game }
        else
          format { render :action => "show" }
          format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
          format.json  { render :json => @game.errors, :status => :unprocessable_entity }
        end
      end
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  Name: <%=f.text_field :name %><br />
  Hare: <%= f.text_field :hare %><br />
  Co-Hares: <%= f.text_field :co_hares %><br />
  Hounds: <%= f.text_field :hounds %><br />
  Created: <%= f.text_field :created_at %><br />
  Started: <%= f.text_field :started_at %><br />
  Location: <%#= f.text_field :location %><br />

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Game Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.name%>:</td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

Name: <%= @game.name%><br />
Hare: <%= @game.hare%><br />
Co-Hares: <%= @game.co_hares.join(", ")%><br />
Hounds: <%= @game.hounds.join(", ")%><br />
Created: <%= @game.created_at %><br />
Started: <%= @game.started_at %><br />
Location: <%#= @game.location.to_s %><br />
<br />
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %> | 
<%= link_to 'Start Game', start_game_path %> | 
<%= link_to 'End Game', end_game_path %> | 
<%= link_to 'Show JSON', game_path(@game, :format => "json") %>